// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://raw.githubusercontent.com' | (string & {});
};

export type CustomTimeStamp = string;

export type User = {
    fullName?: string;
    nickName?: string;
    email?: string;
    reminderEnabled?: boolean;
    reminderTime?: string;
};

export type RegisterRequest = {
    nickname: string;
    fullname: string;
    email: string;
    password: string;
    passwordConfirmation: string;
};

export type LoginRequest = {
    nickname?: string;
    email?: string;
    password: string;
};

export type ConsumptionLog = {
    id?: string;
    itemName?: string;
    itemCategory?: 'makanan & minuman' | 'fashion' | 'elektronik' | 'perawatan diri' | 'hiburan' | 'lainnya';
    itemCategoryCustom?: string | null;
    amount?: number;
    consumedAt?: string;
};

export type AddConsumptionRequest = {
    itemName: string;
    itemCategory: 'makanan & minuman' | 'fashion' | 'elektronik' | 'perawatan diri' | 'hiburan' | 'lainnya';
    itemCategoryCustom?: string;
    amount: number;
    notes?: string;
    consumedAt?: string;
};

export type ConsumptionInsights = {
    streak?: number;
    weekly_summary?: Array<{
        category?: string;
        total?: number;
    }>;
    monthly_summary?: Array<{
        category?: string;
        total?: number;
    }>;
    wishlist_count?: number;
    active_challenge?: number;
};

export type WishlistItem = {
    id?: string;
    itemName?: string;
    itemCategory?: 'makanan & minuman' | 'fashion' | 'elektronik' | 'perawatan diri' | 'hiburan' | 'lainnya';
    itemCategoryCustom?: string | null;
    estimatePrice?: number;
    waitingDays?: number;
    whislistStatus?: string;
    wishlistDaysRemaining?: number;
};

export type AddWishlistRequest = {
    itemName: string;
    itemCategory: 'makanan & minuman' | 'fashion' | 'elektronik' | 'perawatan diri' | 'hiburan' | 'lainnya';
    itemCategoryCustom?: string;
    estimatePrice: number;
    waitingDays: 3 | 7 | 14 | 30;
    reason?: string;
};

export type UpdateWishlistStatusRequest = {
    whislistStatus: 'waiting' | 'bought' | 'cancelled';
};

export type Challenge = {
    id?: string;
    title?: string;
    description?: string;
    fullDescription?: string;
    rules?: string;
    howTo?: string;
    challengesCategory?: 'Zero Waste' | 'No Impulse Buy' | 'Eco Eating' | 'SecondHand' | 'LowSpend';
    imageUrl?: string;
    durationDays?: number;
    startDate?: string;
    endDate?: string;
    status?: 'active' | 'inactive';
    createdAt?: string;
    updatedAt?: string;
    participantCount?: number;
};

export type CreateChallengeRequest = {
    title: string;
    description: string;
    fullDescription: string;
    rules?: string;
    howTo?: string;
    challengesCategory: 'Zero Waste' | 'No Impulse Buy' | 'Eco Eating' | 'SecondHand' | 'LowSpend';
    imageUrl?: string;
    durationDays?: number;
    startDate?: string;
    endDate?: string;
    status?: 'active' | 'inactive';
};

export type UserChallenge = {
    challengeId?: string;
    title?: string;
    joinedAt?: string;
    progress?: number;
};

export type AdminOverview = {
    totalUsers?: number;
    totalConsumptionLogs?: number;
    totalCancelledImpulse?: number;
    totalActiveChallenges?: number;
};

export type AdminUserList = {
    success?: boolean;
    message?: string;
    data?: {
        data?: Array<User>;
        meta?: {
            page?: number;
            limit?: number;
            total?: number;
            totalPages?: number;
            next?: number | null;
            prev?: number | null;
        };
    };
};

export type AdminMonitoring = {
    dailyActiveUsers?: Array<{
        date?: string;
        totalActiveUsers?: number;
    }>;
    dailyLogs?: Array<{
        date?: string;
        totalItems?: number;
    }>;
    topChallenges?: Array<{
        challengeTitle?: string;
        totalParticipants?: number;
    }>;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    password: string;
    passwordConfirmation: string;
    token: string;
};

export type ErrorResponse = {
    success?: boolean;
    message?: string;
};

export type ValidationError = {
    success?: boolean;
    message?: string;
    errors?: Array<{
        path?: string;
        message?: string;
    }>;
};

export type PostAuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Validasi gagal
     */
    400: ValidationError;
    /**
     * Email atau nickname sudah terdaftar
     */
    409: ErrorResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Register berhasil
     */
    201: {
        success?: boolean;
        message?: string;
        data?: {
            id?: string;
        };
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Kredensial salah
     */
    401: ErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login berhasil
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            accessToken?: string;
            refreshToken?: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Refresh token tidak valid atau kadaluarsa
     */
    401: ErrorResponse;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * Refresh berhasil
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            accessToken?: string;
        };
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout berhasil
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type PostAuthForgotPasswordResponses = {
    /**
     * Email reset password dikirim
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostAuthForgotPasswordResponse = PostAuthForgotPasswordResponses[keyof PostAuthForgotPasswordResponses];

export type PostAuthResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordResponses = {
    /**
     * Password berhasil direset
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile';
};

export type GetProfileErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * Berhasil mengambil profil
     */
    200: {
        success?: boolean;
        message?: string;
        data?: User;
    };
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type PatchProfileReminderSettingsData = {
    body: {
        opt_in?: boolean;
        reminder_time?: string;
    };
    path?: never;
    query?: never;
    url: '/profile/reminder-settings';
};

export type PatchProfileReminderSettingsErrors = {
    /**
     * Validasi gagal
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type PatchProfileReminderSettingsError = PatchProfileReminderSettingsErrors[keyof PatchProfileReminderSettingsErrors];

export type PatchProfileReminderSettingsResponses = {
    /**
     * Settings berhasil diupdate
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PatchProfileReminderSettingsResponse = PatchProfileReminderSettingsResponses[keyof PatchProfileReminderSettingsResponses];

export type GetConsumptionLogsData = {
    body?: never;
    path?: never;
    query?: {
        category?: string;
        sortBy?: 'consumedAt' | 'amount' | 'createdAt';
        order?: 'asc' | 'desc';
        startDate?: string;
        endDate?: string;
    };
    url: '/consumption-logs';
};

export type GetConsumptionLogsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetConsumptionLogsError = GetConsumptionLogsErrors[keyof GetConsumptionLogsErrors];

export type GetConsumptionLogsResponses = {
    /**
     * Berhasil mengambil data
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<ConsumptionLog>;
    };
};

export type GetConsumptionLogsResponse = GetConsumptionLogsResponses[keyof GetConsumptionLogsResponses];

export type PostConsumptionLogsData = {
    body: AddConsumptionRequest;
    path?: never;
    query?: never;
    url: '/consumption-logs';
};

export type PostConsumptionLogsErrors = {
    /**
     * Validasi gagal
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type PostConsumptionLogsError = PostConsumptionLogsErrors[keyof PostConsumptionLogsErrors];

export type PostConsumptionLogsResponses = {
    /**
     * Berhasil ditambahkan
     */
    201: {
        success?: boolean;
        message?: string;
        data?: ConsumptionLog;
    };
};

export type PostConsumptionLogsResponse = PostConsumptionLogsResponses[keyof PostConsumptionLogsResponses];

export type DeleteConsumptionLogsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/consumption-logs/{id}';
};

export type DeleteConsumptionLogsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Data tidak ditemukan
     */
    404: ErrorResponse;
};

export type DeleteConsumptionLogsByIdError = DeleteConsumptionLogsByIdErrors[keyof DeleteConsumptionLogsByIdErrors];

export type DeleteConsumptionLogsByIdResponses = {
    /**
     * Berhasil dihapus
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type DeleteConsumptionLogsByIdResponse = DeleteConsumptionLogsByIdResponses[keyof DeleteConsumptionLogsByIdResponses];

export type PutConsumptionLogsByIdData = {
    body: AddConsumptionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/consumption-logs/{id}';
};

export type PutConsumptionLogsByIdErrors = {
    /**
     * Validasi gagal
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Data tidak ditemukan
     */
    404: ErrorResponse;
};

export type PutConsumptionLogsByIdError = PutConsumptionLogsByIdErrors[keyof PutConsumptionLogsByIdErrors];

export type PutConsumptionLogsByIdResponses = {
    /**
     * Berhasil diupdate
     */
    200: {
        success?: boolean;
        message?: string;
        data?: ConsumptionLog;
    };
};

export type PutConsumptionLogsByIdResponse = PutConsumptionLogsByIdResponses[keyof PutConsumptionLogsByIdResponses];

export type GetDashboardInsightData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/insight';
};

export type GetDashboardInsightErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetDashboardInsightError = GetDashboardInsightErrors[keyof GetDashboardInsightErrors];

export type GetDashboardInsightResponses = {
    /**
     * Berhasil mengambil data
     */
    200: {
        success?: boolean;
        message?: string;
        data?: ConsumptionInsights;
    };
};

export type GetDashboardInsightResponse = GetDashboardInsightResponses[keyof GetDashboardInsightResponses];

export type GetWishlistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wishlist';
};

export type GetWishlistErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetWishlistError = GetWishlistErrors[keyof GetWishlistErrors];

export type GetWishlistResponses = {
    /**
     * Berhasil mengambil data
     */
    200: {
        status?: string;
        message?: string;
        data?: Array<WishlistItem>;
    };
};

export type GetWishlistResponse = GetWishlistResponses[keyof GetWishlistResponses];

export type PostWishlistData = {
    body: AddWishlistRequest;
    path?: never;
    query?: never;
    url: '/wishlist';
};

export type PostWishlistErrors = {
    /**
     * Validasi gagal
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type PostWishlistError = PostWishlistErrors[keyof PostWishlistErrors];

export type PostWishlistResponses = {
    /**
     * Berhasil ditambahkan
     */
    201: {
        status?: string;
        message?: string;
        data?: WishlistItem;
    };
};

export type PostWishlistResponse = PostWishlistResponses[keyof PostWishlistResponses];

export type PatchWishlistByIdData = {
    body: UpdateWishlistStatusRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/wishlist/{id}';
};

export type PatchWishlistByIdErrors = {
    /**
     * Validasi gagal
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Data tidak ditemukan
     */
    404: ErrorResponse;
};

export type PatchWishlistByIdError = PatchWishlistByIdErrors[keyof PatchWishlistByIdErrors];

export type PatchWishlistByIdResponses = {
    /**
     * Berhasil diupdate
     */
    200: {
        status?: string;
        message?: string;
        data?: WishlistItem;
    };
};

export type PatchWishlistByIdResponse = PatchWishlistByIdResponses[keyof PatchWishlistByIdResponses];

export type GetChallengeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/challenge';
};

export type GetChallengeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetChallengeError = GetChallengeErrors[keyof GetChallengeErrors];

export type GetChallengeResponses = {
    /**
     * Berhasil mengambil daftar challenge aktif
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<Challenge>;
    };
};

export type GetChallengeResponse = GetChallengeResponses[keyof GetChallengeResponses];

export type GetChallengeMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/challenge/me';
};

export type GetChallengeMeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetChallengeMeError = GetChallengeMeErrors[keyof GetChallengeMeErrors];

export type GetChallengeMeResponses = {
    /**
     * Berhasil mengambil daftar challenge yang diikuti
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<UserChallenge>;
    };
};

export type GetChallengeMeResponse = GetChallengeMeResponses[keyof GetChallengeMeResponses];

export type GetChallengeLandingPageChallengeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/challenge/landing-page-challenge';
};

export type GetChallengeLandingPageChallengeResponses = {
    /**
     * Berhasil mengambil 5 challenge terpopuler
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<Challenge>;
    };
};

export type GetChallengeLandingPageChallengeResponse = GetChallengeLandingPageChallengeResponses[keyof GetChallengeLandingPageChallengeResponses];

export type GetChallengeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/challenge/{id}';
};

export type GetChallengeByIdErrors = {
    /**
     * Challenge tidak ditemukan
     */
    404: ErrorResponse;
};

export type GetChallengeByIdError = GetChallengeByIdErrors[keyof GetChallengeByIdErrors];

export type GetChallengeByIdResponses = {
    /**
     * Berhasil mengambil detail challenge
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Challenge;
    };
};

export type GetChallengeByIdResponse = GetChallengeByIdResponses[keyof GetChallengeByIdResponses];

export type PostChallengeByIdJoinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/challenge/{id}/join';
};

export type PostChallengeByIdJoinErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Challenge tidak ditemukan
     */
    404: ErrorResponse;
};

export type PostChallengeByIdJoinError = PostChallengeByIdJoinErrors[keyof PostChallengeByIdJoinErrors];

export type PostChallengeByIdJoinResponses = {
    /**
     * Berhasil bergabung dalam challenge
     */
    201: {
        success?: boolean;
        message?: string;
        data?: UserChallenge;
    };
};

export type PostChallengeByIdJoinResponse = PostChallengeByIdJoinResponses[keyof PostChallengeByIdJoinResponses];

export type GetChallengeByIdParticipantsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/challenge/{id}/participants';
};

export type GetChallengeByIdParticipantsResponses = {
    /**
     * Berhasil mengambil daftar peserta
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<{
            id?: string;
            nickName?: string;
            fullName?: string;
            joinedAt?: string;
        }>;
    };
};

export type GetChallengeByIdParticipantsResponse = GetChallengeByIdParticipantsResponses[keyof GetChallengeByIdParticipantsResponses];

export type PostUploadSignatureData = {
    body: {
        folderType?: 'consumption' | 'challenge';
    };
    path?: never;
    query?: never;
    url: '/upload/signature';
};

export type PostUploadSignatureResponses = {
    /**
     * Signature berhasil didapatkan
     */
    200: {
        success?: boolean;
        data?: {
            signature?: string;
            timestamp?: number;
            apiKey?: string;
            cloudName?: string;
            folder?: string;
        };
    };
};

export type PostUploadSignatureResponse = PostUploadSignatureResponses[keyof PostUploadSignatureResponses];

export type PostHelperAdminCreateData = {
    body: {
        nickname: string;
        fullname: string;
        email: string;
        password: string;
        passwordConfirmation: string;
        specialCode: number;
    };
    path?: never;
    query?: never;
    url: '/helper/admin/create';
};

export type PostHelperAdminCreateErrors = {
    /**
     * Special code salah
     */
    403: unknown;
};

export type PostHelperAdminCreateResponses = {
    /**
     * Admin berhasil dibuat
     */
    201: unknown;
};

export type PostHelperUsersCreateData = {
    body: {
        fullName?: string;
        nickName?: string;
        email?: string;
        password?: string;
    };
    path?: never;
    query?: never;
    url: '/helper/users/create';
};

export type PostHelperUsersCreateResponses = {
    /**
     * User berhasil dibuat
     */
    201: unknown;
};

export type GetHelperUsersGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/helper/users/get/all';
};

export type GetHelperUsersGetAllResponses = {
    /**
     * Daftar user berhasil diambil
     */
    200: unknown;
};

export type GetHelperUsersGetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/helper/users/get/{id}';
};

export type GetHelperUsersGetByIdResponses = {
    /**
     * User berhasil diambil
     */
    200: unknown;
};

export type GetAdminStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/stats';
};

export type GetAdminStatsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden - Admin only
     */
    403: ErrorResponse;
};

export type GetAdminStatsError = GetAdminStatsErrors[keyof GetAdminStatsErrors];

export type GetAdminStatsResponses = {
    /**
     * Berhasil mengambil data overview
     */
    200: {
        success?: boolean;
        message?: string;
        data?: AdminOverview;
    };
};

export type GetAdminStatsResponse = GetAdminStatsResponses[keyof GetAdminStatsResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        status?: 'active' | 'inactive';
        page?: number;
        limit?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden - Admin only
     */
    403: ErrorResponse;
};

export type GetAdminUsersError = GetAdminUsersErrors[keyof GetAdminUsersErrors];

export type GetAdminUsersResponses = {
    /**
     * Berhasil mengambil daftar pengguna
     */
    200: {
        success?: boolean;
        message?: string;
        data?: AdminUserList;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type GetAdminUsersExportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users/export';
};

export type GetAdminUsersExportErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetAdminUsersExportError = GetAdminUsersExportErrors[keyof GetAdminUsersExportErrors];

export type GetAdminUsersExportResponses = {
    /**
     * File CSV berhasil didownload
     */
    200: Blob | File;
};

export type GetAdminUsersExportResponse = GetAdminUsersExportResponses[keyof GetAdminUsersExportResponses];

export type GetAdminMonitoringData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/monitoring';
};

export type GetAdminMonitoringErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetAdminMonitoringError = GetAdminMonitoringErrors[keyof GetAdminMonitoringErrors];

export type GetAdminMonitoringResponses = {
    /**
     * Data monitoring berhasil diambil
     */
    200: {
        success?: boolean;
        message?: string;
        data?: AdminMonitoring;
    };
};

export type GetAdminMonitoringResponse = GetAdminMonitoringResponses[keyof GetAdminMonitoringResponses];

export type GetAdminChallengesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/challenges';
};

export type GetAdminChallengesErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type GetAdminChallengesError = GetAdminChallengesErrors[keyof GetAdminChallengesErrors];

export type GetAdminChallengesResponses = {
    /**
     * Berhasil mengambil semua daftar challenge
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<Challenge>;
    };
};

export type GetAdminChallengesResponse = GetAdminChallengesResponses[keyof GetAdminChallengesResponses];

export type PostAdminChallengesData = {
    body: CreateChallengeRequest;
    path?: never;
    query?: never;
    url: '/admin/challenges';
};

export type PostAdminChallengesErrors = {
    /**
     * Validasi gagal
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
};

export type PostAdminChallengesError = PostAdminChallengesErrors[keyof PostAdminChallengesErrors];

export type PostAdminChallengesResponses = {
    /**
     * Berhasil membuat challenge baru
     */
    201: {
        success?: boolean;
        message?: string;
        data?: Challenge;
    };
};

export type PostAdminChallengesResponse = PostAdminChallengesResponses[keyof PostAdminChallengesResponses];

export type DeleteAdminChallengesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/challenges/{id}';
};

export type DeleteAdminChallengesByIdErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Data tidak ditemukan
     */
    404: ErrorResponse;
};

export type DeleteAdminChallengesByIdError = DeleteAdminChallengesByIdErrors[keyof DeleteAdminChallengesByIdErrors];

export type DeleteAdminChallengesByIdResponses = {
    /**
     * Berhasil menghapus challenge
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Challenge;
    };
};

export type DeleteAdminChallengesByIdResponse = DeleteAdminChallengesByIdResponses[keyof DeleteAdminChallengesByIdResponses];

export type PutAdminChallengesByIdData = {
    body: CreateChallengeRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/challenges/{id}';
};

export type PutAdminChallengesByIdErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Data tidak ditemukan
     */
    404: ErrorResponse;
};

export type PutAdminChallengesByIdError = PutAdminChallengesByIdErrors[keyof PutAdminChallengesByIdErrors];

export type PutAdminChallengesByIdResponses = {
    /**
     * Berhasil memperbarui data challenge
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Challenge;
    };
};

export type PutAdminChallengesByIdResponse = PutAdminChallengesByIdResponses[keyof PutAdminChallengesByIdResponses];
